In [43]:
import matplotlib as mpl
import matplotlib.pyplot as plt
from wmfdata import hive, charting

In [44]:
charting.set_mpl_style()

In [40]:
active_ed_edit_counts = hive.run("""
with apr_active_eds as (
    select
        event_user_text,
        count(*) as content_edits
    from wmf.mediawiki_history mwh
    inner join wmf_raw.mediawiki_project_namespace_map ns_map
    on 
        mwh.wiki_db = ns_map.dbname and
        mwh.page_namespace = ns_map.namespace
    where
        ns_map.snapshot = "2019-04" and
        mwh.snapshot = "2019-04" and
        mwh.event_entity = "revision" and
        mwh.event_type = "create" and
        mwh.event_timestamp between "2019-04" and "2019-05" and
        mwh.event_user_id != 0 and
        ns_map.namespace_is_content = 1
    group by event_user_text
    having content_edits >= 5
)
select
    event_user_text,
    count(*) as edit_count
from apr_active_eds aae 
inner join wmf.mediawiki_history mwh 
on aae.event_user_text = mwh.event_user_text
where
    mwh.snapshot = "2019-04" and
    mwh.event_entity = "revision" and
    mwh.event_type = "create" and
    not mwh.revision_is_deleted_by_page_deletion
group by mwh.event_user_text
""")

In [41]:
active_ed_edit_counts.query("event_user_text == 'WhatamIdoing'")

      event_user_text  edit_count
76195    WhatamIdoing       99789

In [53]:
active_ed_edit_counts["edit_count"].describe(percentiles=[0.01, 0.1, 0.25, 0.5, 0.75, 0.9, 0.99]).apply(lambda x: format(x, 'f'))

count       84865.000000
mean        22754.283639
std        460146.569539
min             1.000000
1%              3.000000
10%             8.000000
25%            24.000000
50%           249.000000
75%          3699.000000
90%         23987.600000
99%        228777.720000
max      53262319.000000
Name: edit_count, dtype: object

In [52]:
active_ed_edit_counts.query("edit_count < 5")

                 event_user_text  edit_count
5       "luisfernandodelasheras"           2
90                         0FEBO           1
149              123portalboy123           3
168                   1387barsam           2
211                       19113s           3
254                    1YoshiSu3           2
292                  2019paulkim           2
420                        34rar           1
437                  3drdprinter           3
536                       5meggz           4
547             621 AM (Bolinao)           2
548       621 AM (Olongapo City)           1
630                        858cv           4
644                   891Hossein           3
925                    ACCIVATOR           3
997                AHMED SIDDIKI           1
1015                    AJ-GS-CA           4
1070                     ALX2020           4
1100                ANDREA SANTA           2
1390                Abcanonymdef           3
1408                  Abdallah32           2
1558                     Abimane           3
1774          Acousticbandavalon           3
1781              Acrowther10460           1
1802                    Acwedler           4
1826                     Adacron           4
1857                 AdamDerMann           2
1942                   Adenas599           1
1950                   Adesirion           1
2060                Adrianathena           1
...                          ...         ...
83296                       乞食マン           1
83392                       凌樂之聲           2
83566                       大的红包           2
83569                        大脚印           3
83593                       太极与道           2
83642                       小山幸容           4
83657                      尾千木花緒           2
83665  山下七海はコンドーム無しの中出セックスが大好きです           3
83677                       山田 ゆ           3
83727                       広瀬慎一           2
83785                我姆斯啦9487666           3
83813                        文啓光           4
83863                    春日太郎35号           1
83913                    杨超越0731           4
83927                       松本大夜           2
83937                        林幼暖           4
84038                        洛天河           4
84095                        潘奕豪           1
84096                       激走戦隊           4
84190                       石井亮作           4
84210                       神秘客人           3
84333                        苦西西           3
84539                        陳宜芳           4
84574                        顏茹蓁           3
84585                       飯塚慎二           2
84653                         검사           2
84654                        게이버           2
84672                  김일성김정일김정은           4
84768                       오색만찬           1
84846                        한스네           1

[1269 rows x 2 columns]